;;-*-coding: utf-8;-*-
(define-abbrev-table 'fundamental-mode-abbrev-table
  '(
    ("ASAP0" "as soon as possible" nil :count 1)
    ("BTW0" "By the way" nil :count 1)
    ("TBH0" "to be honest" nil :count 1)
   ))

(define-abbrev-table 'unicode-emoticons-mode-abbrev-table
  '(
    ("BR0" "🇧🇷" nil :count 0)
    ("IT0" "🇮🇹" nil :count 1)
    ("UK0" "🇬🇧" nil :count 0)
    ("US0" "🇺🇸" nil :count 0)
    ("angry0" "ლ(ಠ益ಠ)ლ" nil :count 0)
    ("awkward0" "(´°ω°`)" nil :count 0)
    ("beer0" "🍺" nil :count 0)
    ("beers0" "🍻" nil :count 0)
    ("birthdaycake0" "🎂" nil :count 0)
    ("bye0" "👋" nil :count 1)
    ("cat0" "(=^･ω･^=)" nil :count 0)
    ("clown0" "🤡" nil :count 0)
    ("confused0" "「(°ヘ°)" nil :count 0)
    ("confusedshrug0" "¯\\(°_o)/¯" nil :count 1)
    ("cool0" "┌(▀Ĺ̯▀)┐" nil :count 0)
    ("crazy0" "🤪" nil :count 0)
    ("cry0" "(T_T)" nil :count 2)
    ("cry1" "😢" nil :count 0)
    ("cry2" "😭" nil :count 1)
    ("cute0" "(◕ᴥ◕)" nil :count 1)
    ("dance0" "┏(-_-)┓┏(-_-)┛┗(-_-﻿ )┓" nil :count 0)
    ("dead0" "(✖╭╮✖)" nil :count 0)
    ("deal0" "🤝" nil :count 0)
    ("death0" "💀" nil :count 0)
    ("delicious0" "😋" nil :count 0)
    ("devil0" "😈" nil :count 0)
    ("disappointed0" "(￣︿￣)" nil :count 0)
    ("disapprove0" "(ಠ_ಠ)" nil :count 0)
    ("disgusting0" "🤢" nil :count 0)
    ("doublefacepalm0" "(ლ‸－)(－‸ლ)" nil :count 0)
    ("doubt0" "(¬､¬)" nil :count 0)
    ("drool0" "🤤" nil :count 0)
    ("excited0" "o(≧▽≦)o" nil :count 0)
    ("facepalm0" "(－‸ლ)" nil :count 0)
    ("fingercrossed0" "🤞" nil :count 0)
    ("fire0" "🔥" nil :count 0)
    ("flex0" "ᕦ( ᴼ ڡ ᴼ )ᕤ" nil :count 0)
    ("flight0" "✈️" nil :count 0)
    ("fliptable0" "(╯°□°）╯︵ ┻━┻" nil :count 0)
    ("flower0" "⚘" nil :count 0)
    ("freeze0" "🥶" nil :count 0)
    ("frowning" "☹" nil :count 0)
    ("grinning0" "😀" nil :count 3)
    ("guitar0" "🎸" nil :count 0)
    ("halloween0" "🎃" nil :count 0)
    ("happy0" "(✿◠‿◠)" nil :count 0)
    ("heart0" "❤" nil :count 5)
    ("heartbreak0" "💔" nil :count 0)
    ("hearteyes0" "(❤ω❤)" nil :count 0)
    ("hello0" "👋" nil :count 0)
    ("hi0" "👋" nil :count 0)
    ("hot0" "🥵" nil :count 0)
    ("hug0" "🤗" nil :count 2)
    ("injury0" "🤕" nil :count 0)
    ("joy0" "＼(＾▽＾)／" nil :count 0)
    ("kiss0" "(￣З￣)♡" nil :count 0)
    ("lol0" "😂" nil :count 13)
    ("love0" "♥‿♥" nil :count 3)
    ("magic0" "(つ◕౪◕)つ━☆ﾟ.*･｡ﾟ" nil :count 0)
    ("meh0" "ヽ║ ˘ _ ˘ ║ノ" nil :count 0)
    ("metal0" "🤘" nil :count 1)
    ("money0" "💵" nil :count 0)
    ("moneylot0" "💰" nil :count 0)
    ("nyan0" "~=[,,_,,]:3" nil :count 0)
    ("ok0" "👌" nil :count 0)
    ("party0" "🥳" nil :count 2)
    ("partypopper0" "🎉" nil :count 3)
    ("pig0" "🐷" nil :count 0)
    ("plane0" "✈️" nil :count 0)
    ("pleased0" "(─‿‿─)" nil :count 0)
    ("pointout0" "(՞ਊ՞)☝" nil :count 0)
    ("pray0" "🙏" nil :count 0)
    ("rain0" "🌧" nil :count 0)
    ("relieved0" "😌" nil :count 0)
    ("rocket0" "🚀" nil :count 0)
    ("rockon0" "\\,,/(^_^)\\,,/" nil :count 0)
    ("rofl0" "🤣" nil :count 3)
    ("sad0" "(T_T)" nil :count 2)
    ("shifty0" "(¬､¬)" nil :count 0)
    ("shit0" "💩" nil :count 0)
    ("shrug0" "¯\\_(ツ)_/¯" nil :count 2)
    ("sick0" "😷" nil :count 0)
    ("smile0" "(◕‿◕)" nil :count 2)
    ("smilesweat0" "😅" nil :count 19)
    ("smiley0" "(◕ل͜◕)" nil :count 0)
    ("snow0" "❅" nil :count 0)
    ("snowman0" "☃" nil :count 0)
    ("sorry0" "🙇" nil :count 0)
    ("spritz0" "🍹" nil :count 0)
    ("ssh0" "🤫" nil :count 0)
    ("stareyes0" "(✯◡✯)" nil :count 0)
    ("stonks0" "📈" nil :count 0)
    ("success0" "(•̀ᴗ•́)و ̑̑" nil :count 0)
    ("sunglasses0" "😎" nil :count 0)
    ("surprised0" "😯" nil :count 0)
    ("think0" "🤔" nil :count 0)
    ("thumbsup0" "d–(^ ‿ ^ )z" nil :count 0)
    ("thumbup0" "👍" nil :count 0)
    ("tired0" "🥱" nil :count 0)
    ("tongue0" "😛" nil :count 3)
    ("top0" "🔝" nil :count 0)
    ("umbrella0" "☂" nil :count 0)
    ("wavehand0" "👋" nil :count 0)
    ("whaa0" "༼⁰o⁰；༽" nil :count 0)
    ("wind0" "🌬" nil :count 0)
    ("wink0" "😉" nil :count 11)
    ("yay0" "٩(⁎❛ᴗ❛⁎)۶" nil :count 0)
    ("yummy0" "😋" nil :count 0)
    ("zzz0" "💤" nil :count 0)
   ))

