;;-*-coding: utf-8;-*-
(define-abbrev-table 'unicode-emoticons-mode-abbrev-table
  '(
    ("angry0" "ლ(ಠ益ಠ)ლ" nil :count 0)
    ("awkward0" "(´°ω°`)" nil :count 0)
    ("bye0" "👋" nil :count 0)
    ("confused0" "「(°ヘ°)" nil :count 0)
    ("confusedshrug0" "¯\\(°_o)/¯" nil :count 0)
    ("cool0" "┌(▀Ĺ̯▀)┐" nil :count 0)
    ("cry0" "ヽ༼ಢ_ಢ༽ﾉ☂" nil :count 0)
    ("csi0" "•_•)
( •_•)>⌐■-■
(⌐■_■)
" nil :count 0)
    ("ctulu0" "^(;,;)^" nil :count 0)
    ("cute0" "(◕ᴥ◕)" nil :count 0)
    ("dance0" "┏(-_-)┓┏(-_-)┛┗(-_-﻿ )┓" nil :count 0)
    ("dead0" "(✖╭╮✖)" nil :count 0)
    ("devil0" "😈" nil :count 0)
    ("disapprove0" "(ಠ_ಠ)" nil :count 0)
    ("doublefacepalm0" "(ლ‸－)(－‸ლ)" nil :count 0)
    ("excited0" "[ ⇀ ‿ ↼ ]" nil :count 0)
    ("facepalm0" "(－‸ლ)" nil :count 0)
    ("fingercrossed0" "🤞" nil :count 0)
    ("fivedollars0" "[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]" nil :count 0)
    ("flex0" "ᕦ( ᴼ ڡ ᴼ )ᕤ" nil :count 0)
    ("fliptable0" "(╯°□°）╯︵ ┻━┻" nil :count 0)
    ("flower0" "⚘" nil :count 0)
    ("gimme0" "༼ つ ◕_◕ ༽つ" nil :count 0)
    ("grinning0" "😀" nil :count 1)
    ("happy0" "(✿◠‿◠)" nil :count 0)
    ("hatersgonnahate0" "ᕕ( ᐛ )ᕗ" nil :count 0)
    ("heart0" "❤" nil :count 0)
    ("hug0" "🤗" nil :count 0)
    ("lol0" "😂" nil :count 2)
    ("love0" "♥‿♥" nil :count 0)
    ("magic0" "(つ◕౪◕)つ━☆ﾟ.*･｡ﾟ" nil :count 0)
    ("meh0" "ヽ║ ˘ _ ˘ ║ノ" nil :count 0)
    ("metal0" "🤘" nil :count 0)
    ("nyan0" "~=[,,_,,]:3" nil :count 0)
    ("orly0" "﴾͡๏̯͡๏﴿ O'RLY?" nil :count 0)
    ("pingpong0" "( •_•)O*¯`·.¸.·´¯`°Q(•_• )" nil :count 0)
    ("pleased0" "(─‿‿─)" nil :count 0)
    ("pointout0" "( ՞ਊ ՞)☝" nil :count 0)
    ("potter0" "(̶◉͛‿◉̶)" nil :count 0)
    ("raiseyourdongers0" "ヽ༼ຈل͜ຈ༽ﾉ" nil :count 0)
    ("rockon0" "\\,,/(^_^)\\,,/" nil :count 0)
    ("rofl0" "🤣" nil :count 0)
    ("sad0" "(╯_╰)" nil :count 0)
    ("shifty0" "(¬､¬)" nil :count 0)
    ("shrug0" "¯\\_(ツ)_/¯" nil :count 0)
    ("smile0" "(◕‿◕)" nil :count 1)
    ("smilesweat0" "😅" nil :count 6)
    ("smiley0" "(◕ل͜◕)" nil :count 0)
    ("snow0" "❅" nil :count 0)
    ("snowman0" "☃" nil :count 0)
    ("success0" "(•̀ᴗ•́)و ̑̑" nil :count 0)
    ("sunglasses0" "😎" nil :count 0)
    ("surprised0" "ﾉﾟ0ﾟ)ﾉ" nil :count 0)
    ("tears0" "༼ ༎ຶ ෴ ༎ຶ༽" nil :count 0)
    ("think0" "🤔" nil :count 0)
    ("thumbsup0" "d–(^ ‿ ^ )z" nil :count 0)
    ("thumbup0" "👍" nil :count 0)
    ("tongue0" "😛" nil :count 0)
    ("umbrella0" "☂" nil :count 0)
    ("whaa0" "༼⁰o⁰；༽" nil :count 0)
    ("wink0" "😉" nil :count 4)
    ("yay0" "٩(⁎❛ᴗ❛⁎)۶" nil :count 0)
    ("yesss0" "(งಠ_ಠ)ง" nil :count 0)
    ("yuno0" "щ(゜ロ゜щ)" nil :count 0)
   ))

